// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Matic Platform Engineering"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/forms": {
            "get": {
                "description": "Lists all forms (tables with icon \"form\") in a workspace for an authenticated member.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forms"
                ],
                "summary": "List forms in a workspace",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.FormDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new form (a data table with icon \"form\") plus its associated form view.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forms"
                ],
                "summary": "Create a form",
                "parameters": [
                    {
                        "description": "Form to create",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateFormInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.FormDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/forms/by-slug/{slug}": {
            "get": {
                "description": "Resolves a form by its auto-generated slug, custom_slug, or (if a UUID is passed) its ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forms"
                ],
                "summary": "Get a form by slug",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Form slug, custom slug, or ID",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.FormDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/forms/by-subdomain/{subdomain}/{slug}": {
            "get": {
                "description": "Resolves a form for pretty public portal URLs of the form {subdomain}.maticapp.com/{slug}.\nAuto-creates a form view (unpublished) if one doesn't exist yet.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forms"
                ],
                "summary": "Resolve a form by workspace subdomain + slug",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace custom subdomain",
                        "name": "subdomain",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Form slug, custom slug, or ID",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.PortalFormDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/forms/list": {
            "get": {
                "description": "Fast endpoint for the Applications Hub — lists forms in a workspace without loading form\nfields, and includes submission counts merged from legacy and new-schema submissions.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forms"
                ],
                "summary": "List forms (optimized)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.FormListItemDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/forms/{id}": {
            "get": {
                "description": "Returns a single form (backed by a data table with icon \"form\") with its fields and publish state.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forms"
                ],
                "summary": "Get a form by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Form ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.FormDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a form and, within a transaction, all of its rows (submissions) and fields.",
                "tags": [
                    "forms"
                ],
                "summary": "Delete a form",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Form ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "description": "Partially updates a form's name, description, settings, publish state, or preview metadata.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forms"
                ],
                "summary": "Update a form",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Form ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateFormInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.FormDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/forms/{id}/custom-slug": {
            "put": {
                "description": "Sets or clears the custom URL slug used for pretty public portal links.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forms"
                ],
                "summary": "Update a form's custom slug",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Form ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New custom slug (null to remove)",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateFormCustomSlugInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.FormDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/forms/{id}/structure": {
            "put": {
                "description": "Replaces a form's builder structure — settings, sections (with their fields), and translations —\nrebuilding the underlying table fields to match.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forms"
                ],
                "summary": "Replace a form's structure",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Form ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New form structure",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateFormStructureInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/forms/{id}/submission": {
            "get": {
                "description": "Looks up a submission for a form by matching an applicant's email against several known\nfield locations in the row/submission data. Used to resume an in-progress application.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forms"
                ],
                "summary": "Get a form submission by applicant email",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Form ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Applicant email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/forms/{id}/submissions": {
            "get": {
                "description": "Lists submissions for a form. Tries the new form_submissions schema first (raw_data),\nfalling back to the legacy table_rows-backed submissions.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forms"
                ],
                "summary": "List submissions for a form",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Form ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Include submitter user info",
                        "name": "include_user",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/forms/{id}/submissions/{submission_id}": {
            "delete": {
                "description": "Permanently deletes a single form submission (row) by its ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forms"
                ],
                "summary": "Delete a form submission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Form ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Submission ID",
                        "name": "submission_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/forms/{id}/submit": {
            "post": {
                "description": "Creates a new submission (row) for a published form and queues it for semantic embedding.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forms"
                ],
                "summary": "Submit a form",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Form ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Submission data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.SubmitFormInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Row"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tables": {
            "get": {
                "description": "Lists data tables, optionally filtered to a workspace. When workspace_id is supplied, the\ncaller must be an authenticated member of that workspace; results are further restricted\nto the member's hub_access list when one is configured.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tables"
                ],
                "summary": "List data tables",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID to filter tables by",
                        "name": "workspace_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Table"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new data table in a workspace. A unique slug is derived from the name automatically.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tables"
                ],
                "summary": "Create a data table",
                "parameters": [
                    {
                        "description": "Table to create",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateDataTableInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Table"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tables/{id}": {
            "get": {
                "description": "Gets a single data table by ID, with its visible (non-layout) fields and recent views preloaded.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tables"
                ],
                "summary": "Get a data table",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Table ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Table"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Permanently deletes a data table.",
                "tags": [
                    "tables"
                ],
                "summary": "Delete a data table",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Table ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "description": "Partially updates a data table's name, description, icon, or settings.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tables"
                ],
                "summary": "Update a data table",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Table ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateDataTableInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Table"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tables/{id}/columns": {
            "post": {
                "description": "Creates a new column (field) on a table, resolving defaults from the field type registry.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tables"
                ],
                "summary": "Create a table column",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Table ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Column to create",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateTableColumnInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Field"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tables/{id}/columns/{column_id}": {
            "delete": {
                "tags": [
                    "tables"
                ],
                "summary": "Delete a table column",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Table ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Column ID",
                        "name": "column_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "description": "Partially updates a column's metadata and config (width, visibility, validation, etc).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tables"
                ],
                "summary": "Update a table column",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Table ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Column ID",
                        "name": "column_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateTableColumnInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Field"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tables/{id}/rows": {
            "get": {
                "description": "Retrieves rows for a table with pagination (default limit 100, max 500).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tables"
                ],
                "summary": "List rows for a table",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Table ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Max rows to return (1-500, default 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Row offset for pagination",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new row in a table and queues it for version history and semantic embedding.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tables"
                ],
                "summary": "Create a table row",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Table ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Row to create",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateTableRowInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Row"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tables/{id}/rows/{row_id}": {
            "get": {
                "description": "Retrieves a single row by ID, scoped to its parent table.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tables"
                ],
                "summary": "Get a table row",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Table ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Row ID",
                        "name": "row_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Row"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "tables"
                ],
                "summary": "Delete a table row",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Table ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Row ID",
                        "name": "row_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "description": "Updates a row's data/position within a transaction, recording a version and field-change diff.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tables"
                ],
                "summary": "Update a table row",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Table ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Row ID",
                        "name": "row_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateTableRowInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Row"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.CreateDataTableInput": {
            "type": "object",
            "required": [
                "name",
                "workspace_id"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "settings": {
                    "type": "object",
                    "additionalProperties": true
                },
                "workspace_id": {
                    "type": "string"
                }
            }
        },
        "handlers.CreateFormInput": {
            "type": "object",
            "required": [
                "name",
                "workspace_id"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "is_published": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "settings": {
                    "type": "object",
                    "additionalProperties": true
                },
                "workspace_id": {
                    "type": "string"
                }
            }
        },
        "handlers.CreateTableColumnInput": {
            "type": "object",
            "required": [
                "name",
                "type"
            ],
            "properties": {
                "is_primary": {
                    "description": "Maps to is_primary in DB",
                    "type": "boolean"
                },
                "is_visible": {
                    "type": "boolean"
                },
                "label": {
                    "description": "Display label (defaults to name if not provided)",
                    "type": "string"
                },
                "linked_table_id": {
                    "description": "For link columns",
                    "type": "string"
                },
                "name": {
                    "description": "TableID is optional in body - we use URL param instead",
                    "type": "string"
                },
                "options": {
                    "type": "object",
                    "additionalProperties": true
                },
                "position": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "validation": {
                    "type": "object",
                    "additionalProperties": true
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "handlers.CreateTableRowInput": {
            "type": "object",
            "required": [
                "data"
            ],
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": true
                },
                "position": {
                    "type": "integer"
                }
            }
        },
        "handlers.FieldInput": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.FieldInput"
                    }
                },
                "config": {
                    "description": "Additional config like dynamicOptions, sourceField, etc.",
                    "type": "object",
                    "additionalProperties": true
                },
                "id": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "placeholder": {
                    "type": "string"
                },
                "position": {
                    "type": "integer"
                },
                "required": {
                    "type": "boolean"
                },
                "type": {
                    "type": "string"
                },
                "validation": {
                    "type": "object",
                    "additionalProperties": true
                },
                "width": {
                    "description": "Can be string (\"full\", \"half\") or number"
                }
            }
        },
        "handlers.FormDTO": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "custom_slug": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Field"
                    }
                },
                "id": {
                    "type": "string"
                },
                "is_published": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "preview_description": {
                    "type": "string"
                },
                "preview_image_url": {
                    "type": "string"
                },
                "preview_title": {
                    "description": "Preview/Share metadata",
                    "type": "string"
                },
                "settings": {
                    "type": "object",
                    "additionalProperties": true
                },
                "slug": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "view_id": {
                    "type": "string"
                },
                "workspace_id": {
                    "type": "string"
                }
            }
        },
        "handlers.FormListItemDTO": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "custom_slug": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_published": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "preview_description": {
                    "type": "string"
                },
                "preview_image_url": {
                    "type": "string"
                },
                "preview_title": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "submission_count": {
                    "description": "Optional: count of submissions",
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "view_id": {
                    "type": "string"
                },
                "workspace_id": {
                    "type": "string"
                }
            }
        },
        "handlers.PortalFormDTO": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "custom_slug": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Field"
                    }
                },
                "id": {
                    "type": "string"
                },
                "is_published": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "preview_description": {
                    "type": "string"
                },
                "preview_image_url": {
                    "type": "string"
                },
                "preview_title": {
                    "description": "Preview/Share metadata",
                    "type": "string"
                },
                "settings": {
                    "type": "object",
                    "additionalProperties": true
                },
                "slug": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "view_id": {
                    "type": "string"
                },
                "workspace_id": {
                    "type": "string"
                },
                "workspace_name": {
                    "type": "string"
                },
                "workspace_subdomain": {
                    "type": "string"
                }
            }
        },
        "handlers.SectionInput": {
            "type": "object",
            "properties": {
                "blocks": {
                    "description": "Ending section blocks",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "conditions": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "content": {
                    "description": "Cover section content (Novel editor)",
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.FieldInput"
                    }
                },
                "id": {
                    "type": "string"
                },
                "sectionType": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "handlers.SubmitFormInput": {
            "type": "object",
            "required": [
                "data"
            ],
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": true
                },
                "email": {
                    "type": "string"
                },
                "save_draft": {
                    "description": "If true, don't mark as submitted",
                    "type": "boolean"
                }
            }
        },
        "handlers.UpdateDataTableInput": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "settings": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "handlers.UpdateFormCustomSlugInput": {
            "type": "object",
            "properties": {
                "custom_slug": {
                    "description": "Can be null to remove custom slug",
                    "type": "string"
                }
            }
        },
        "handlers.UpdateFormInput": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "is_published": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "preview_description": {
                    "type": "string"
                },
                "preview_image_url": {
                    "type": "string"
                },
                "preview_title": {
                    "description": "Preview/Share metadata",
                    "type": "string"
                },
                "settings": {
                    "type": "object",
                    "additionalProperties": true
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "handlers.UpdateFormStructureInput": {
            "type": "object",
            "properties": {
                "sections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.SectionInput"
                    }
                },
                "settings": {
                    "type": "object",
                    "additionalProperties": true
                },
                "translations": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "handlers.UpdateTableColumnInput": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "is_primary": {
                    "type": "boolean"
                },
                "is_visible": {
                    "type": "boolean"
                },
                "label": {
                    "type": "string"
                },
                "linked_table_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "options": {
                    "type": "object",
                    "additionalProperties": true
                },
                "placeholder": {
                    "type": "string"
                },
                "position": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "validation": {
                    "type": "object",
                    "additionalProperties": true
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "handlers.UpdateTableRowInput": {
            "type": "object",
            "properties": {
                "change_reason": {
                    "description": "Optional reason for the change",
                    "type": "string"
                },
                "data": {
                    "type": "object",
                    "additionalProperties": true
                },
                "position": {
                    "type": "integer"
                }
            }
        },
        "models.Field": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Field"
                    }
                },
                "config": {
                    "description": "Instance configuration (merged with registry default_config)",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "description": "Field description",
                    "type": "string"
                },
                "field_type": {
                    "description": "Relationships (populated when preloading)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.FieldTypeRegistry"
                        }
                    ]
                },
                "field_type_id": {
                    "description": "References field_type_registry.id",
                    "type": "string"
                },
                "formula": {
                    "description": "Calculated field formula",
                    "type": "string"
                },
                "formula_dependencies": {
                    "description": "Fields formula depends on",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "is_display_field": {
                    "description": "Use as display in links",
                    "type": "boolean"
                },
                "is_primary": {
                    "description": "Primary display field",
                    "type": "boolean"
                },
                "is_searchable": {
                    "description": "Include in search",
                    "type": "boolean"
                },
                "is_visible": {
                    "description": "Show in table view",
                    "type": "boolean"
                },
                "label": {
                    "description": "Display name",
                    "type": "string"
                },
                "linked_column_id": {
                    "description": "Display column for link",
                    "type": "string"
                },
                "linked_table_id": {
                    "description": "For link fields",
                    "type": "string"
                },
                "name": {
                    "description": "Internal key",
                    "type": "string"
                },
                "parent_field_id": {
                    "description": "For nested fields (group/repeater children)",
                    "type": "string"
                },
                "position": {
                    "description": "Display order",
                    "type": "integer"
                },
                "rollup_function": {
                    "description": "Aggregation function for rollups",
                    "type": "string"
                },
                "sample_values": {
                    "description": "Cached sample values",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "search_weight": {
                    "description": "Search ranking weight",
                    "type": "number"
                },
                "section_id": {
                    "description": "Form section this field belongs to (matches settings.sections[].id)",
                    "type": "string"
                },
                "semantic_type": {
                    "description": "name, email, phone, status, date, etc.",
                    "type": "string"
                },
                "settings": {
                    "description": "Type-specific settings (legacy)",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "table_id": {
                    "type": "string"
                },
                "type": {
                    "description": "text, number, select, link, etc. (legacy, use field_type_id)",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "validation": {
                    "description": "Validation rules (legacy)",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "width": {
                    "description": "Column width in pixels",
                    "type": "integer"
                }
            }
        },
        "models.FieldTypeRegistry": {
            "type": "object",
            "properties": {
                "ai_schema": {
                    "description": "AI Integration",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "category": {
                    "description": "primitive, container, layout, special",
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "config_schema": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "default_config": {
                    "description": "Default settings for new fields",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "default_semantic_type": {
                    "description": "Semantic type mapping",
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "form_renderer": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "description": "'text', 'email', 'repeater', etc.",
                    "type": "string"
                },
                "input_schema": {
                    "description": "Schema definitions (JSON Schema format)",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "is_container": {
                    "description": "Behavior flags",
                    "type": "boolean"
                },
                "is_editable": {
                    "type": "boolean"
                },
                "is_filterable": {
                    "type": "boolean"
                },
                "is_searchable": {
                    "type": "boolean"
                },
                "is_sortable": {
                    "type": "boolean"
                },
                "label": {
                    "type": "string"
                },
                "require_reason": {
                    "type": "boolean"
                },
                "review_renderer": {
                    "type": "string"
                },
                "storage_schema": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "supports_pii": {
                    "type": "boolean"
                },
                "table_renderer": {
                    "description": "Rendering hints",
                    "type": "string"
                },
                "track_changes": {
                    "description": "Edit tracking settings",
                    "type": "boolean"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Row": {
            "type": "object",
            "properties": {
                "ba_created_by": {
                    "description": "Better Auth user ID (TEXT)",
                    "type": "string"
                },
                "ba_updated_by": {
                    "description": "Better Auth user ID (TEXT)",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "id": {
                    "type": "string"
                },
                "is_archived": {
                    "type": "boolean"
                },
                "metadata": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "position": {
                    "description": "bigint in database",
                    "type": "integer"
                },
                "stage_group_id": {
                    "type": "string"
                },
                "table_id": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Table": {
            "type": "object",
            "properties": {
                "ai_settings": {
                    "description": "AI suggestion settings",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "approval_settings": {
                    "description": "Change approval config",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "ba_created_by": {
                    "description": "Better Auth user ID (TEXT)",
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "columns": {
                    "description": "Relationships",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Field"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "custom_slug": {
                    "description": "Optional custom URL for public portals",
                    "type": "string"
                },
                "dashboard_layout": {
                    "description": "Applicant dashboard configuration (builder-defined layout for portal users)",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "description": {
                    "type": "string"
                },
                "entity_type": {
                    "description": "person, event, application, etc.",
                    "type": "string"
                },
                "history_settings": {
                    "description": "Version history config",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "hub_type": {
                    "description": "activities, applications, data",
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "import_metadata": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "import_source": {
                    "description": "Where data was imported from",
                    "type": "string"
                },
                "is_archived": {
                    "type": "boolean"
                },
                "is_hidden": {
                    "description": "Hide from navigation and overview for all users",
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "preview_description": {
                    "type": "string"
                },
                "preview_image_url": {
                    "type": "string"
                },
                "preview_title": {
                    "description": "Share preview metadata (for forms/portals)",
                    "type": "string"
                },
                "row_count": {
                    "type": "integer"
                },
                "rows": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Row"
                    }
                },
                "settings": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "slug": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "views": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.View"
                    }
                },
                "workspace_id": {
                    "type": "string"
                }
            }
        },
        "models.View": {
            "type": "object",
            "properties": {
                "ba_created_by": {
                    "description": "Better Auth user ID (TEXT)",
                    "type": "string"
                },
                "config": {
                    "description": "For portal: sections, translations, theme",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "filters": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "grouping": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "id": {
                    "type": "string"
                },
                "is_locked": {
                    "type": "boolean"
                },
                "is_shared": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "settings": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "sorts": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "table_id": {
                    "type": "string"
                },
                "type": {
                    "description": "grid, form, kanban, gallery, calendar, timeline, portal",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Better Auth session token, sent as \"Authorization: Bearer \u003ctoken\u003e\" or via session cookie.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Matic Platform API",
	Description:      "Go/Gin backend for the Matic Platform. This spec is generated incrementally via swaggo/swag —\nonly the Tables (data_tables.go) and Forms (forms.go) handler domains are annotated so far.\nSee docs/API_CLIENT_CODEGEN.md for how to extend this to other handler domains.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
